# Generated by Django 5.2.13 on 2026-06-02 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiMua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tai_khoan', models.CharField(max_length=255, unique=True)),
                ('mat_khau', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=255, null=True)),
                ('ten', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Người mua',
                'verbose_name_plural': 'Người mua',
            },
        ),
    ]
