# Generated by Django 5.2.13 on 2026-06-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('trang_thai', models.SmallIntegerField(choices=[(0, 'Chờ xử lý'), (1, 'Đang giao'), (2, 'Đã giao'), (3, 'Đã hủy')], default=0, verbose_name='Trạng thái')),
                ('ngay_dat', models.DateField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('ngay_nhan_du_kien', models.DateField(blank=True, null=True, verbose_name='Ngày nhận dự kiến')),
                ('id_chu_shop', models.IntegerField(blank=True, null=True, verbose_name='ID Chủ shop')),
                ('nguoi_mua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nguoimua', verbose_name='Người mua')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_san_pham', models.IntegerField(verbose_name='Số lượng')),
                ('gia_mua', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá mua lúc đặt')),
                ('bien_the', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.bienthesanpham', verbose_name='Biến thể sản phẩm')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cart.donhang', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('ngay_them', models.DateField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('bien_the', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bienthesanpham', verbose_name='Biến thể sản phẩm')),
                ('nguoi_mua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nguoimua', verbose_name='Người mua')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
