# Generated by Django 5.2.13 on 2026-06-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255, verbose_name='Tên giày')),
                ('thuong_hieu', models.CharField(max_length=255, verbose_name='Thương hiệu')),
                ('gia_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá tiền')),
                ('id_chu_shop', models.IntegerField(blank=True, null=True, verbose_name='ID Chủ shop')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('anh_dai_dien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.SmallIntegerField(verbose_name='Số sao')),
                ('binh_luan', models.TextField(blank=True, null=True, verbose_name='Bình luận')),
                ('ngay_danh_gia', models.DateField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('nguoi_mua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nguoimua', verbose_name='Người mua')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
            },
        ),
        migrations.CreateModel(
            name='BienTheSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Size giày')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu sắc')),
                ('so_luong_ton', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
            },
        ),
    ]
